name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
# version: VERSION
# core: 8.x
hidden: true

# Information added by Drupal.org packaging script on 2019-04-08
version: '8.6.14'
core: '8.x'
project: 'drupal'
datestamp: 1554688420
